version: '3'

services:
  Agent-portal-gateway:
    build:
      context: ../
      dockerfile: OcelotGateway/Dockerfile
    image: ocelot-gateway
    container_name: ocelot-gateway
    ports:
      - 8099:8099
       
  Authentication-service:
    build:
      context: ../
      dockerfile: AuthenticationService/Dockerfile
    image: authentication-service
    container_name: authentication-service
    ports:
      - 6060:6060
      
  File-management-service:
    build:
      context: ../
      dockerfile: FileMananagementService/Dockerfile
    image: file-management-service
    container_name: file-management-service
    ports:
      - 5030:5030
    
  Scheduler-service:
    build:
      context: ../
      dockerfile: SchedulerService/Dockerfile
    image: scheduler-service
    container_name: scheduler-service
    ports:
      - 3030:3030